### ISSUE TITLE
UI Design - The Leaderboard for Friend of Grin

### ISSUE THREAD

**Issue by noahyeh** [mimblewimble/design#9]
Taken by @nijynot 
https://github.com/mimblewimble/grin-pm/issues/52#issuecomment-462708272 , asked by Gary Yu

**Comment by 0xb100d** [comment]
lt 100% should look like an 8-bit arcade leaderboard.
reference: https://www.dailydot.com/wp-content/uploads/caf/92/fb0228aa147e3a45b56324eaddc47945.jpg

**Comment by nijynot** [comment]
mimblewimble/site#106 merged, closing.
